@startuml 
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Context.puml

LAYOUT_WITH_LEGEND()
' Aqui você cria os usuários
Person(cmu, "Common User", "User common that acess the system")
Person(mu, "Master User", "Common User, but has benefits due to monthly subscription.")
Person(sm, "Sales User", "Common User, but can publish product")
Person(mkt, "Marketing User", "Manager ads, Analysis of likes,Profile analysis of users")
Person(adm, "Administrator", "Admin User with all privileges to perform system moderation.")

System(readchat, "ReadChat", "SOCIAL NETWORK WITH THE POSSIBILITY OF POSTING VIDEOS AND FILES AND SELLING PRODUCTS")
System_Ext(eml, "E-mail System", "Email system to notify the user via email services.")
System_Ext(bsy, "Bank System API", "Banking services API, for monetary transfer between users.")

Rel(cmu, mu, "extends")
Rel(cmu, sm, "extends")
Rel(cmu, mkt, "extends")
Rel(cmu, readchat, "Uses", "HTTPS")
Rel(adm, readchat, "Uses", "HTTPS")
Rel(mu, readchat, "Uses", "HTTPS")
Rel(sm,readchat, "Uses", "HTTPS")
Rel(mkt, readchat, "Uses", "HTTPS")
Rel(readchat, eml, "Uses")
Rel(readchat, bsy, "Uses")

@enduml
