@startuml
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Container.puml

LAYOUT_WITH_LEGEND()

Person(cms, "Common User", "User common that acess the system")
Person(mu, "Administrator", "Create User and Delete user and Moderated publish")
Person(sm, "SalesMan", "publish product")
Person(ma, "Marketing  Manager ads, Analysis of likes,Profile analysis of users")

System_Boundary(ModuleLogin, "ReadChat module User login") {
    Container(wbLogin, "Web Application", "java and Spring MVC", "Delivers the static content and the internet banking single page application.")
    Container(dbLogin, "Database", "Relational Database Schema", "Stores user registration information, hashed authentication credentials, access logs, etc.")
    Container(apiLogin, "API Application", "java and String MVC", "Provides internet banking functionality via a JSON/HTTP API.")
    Rel(apiLogin, dbLogin, "Reads & writes to", "JDBC")
    Rel(wbLogin, apiLogin, "Delivers")
}

Rel(cms, wbLogin, "Uses", "HTTPS")




System_Boundary(ModuleAdmin, "ReadChat module Admin User") {
    Container(wbAdmin, "Web Application", "java and Spring MVC", "Delivers the static content and the internet banking single page application.")
    Container(dbAdmin, "Database", "Relational Database Schema", "Stores user registration information, hashed authentication credentials, access logs, etc.")
    Container(apiAdmin, "API Application Admin", "java and String MVC", "Provides internet banking functionality via a JSON/HTTP API.")

    Rel(apiAdmin, dbAdmin, "Reads & writes to", "JDBC")
    Rel(wbAdmin, apiAdmin, "Delivers")
    
}

Rel(mu, wbAdmin, "Uses", "HTTPS")



System_Boundary(ModuleSales, "ReadChat module Sales"){
       Container(wbSales, "Web Application", "java and Spring MVC", "Delivers the static content and the internet banking single page application.")
       Container(dbSales, "Database", "Relational Database Schema", "Stores user registration information, hashed authentication credentials, access logs, etc.")
       Container(apiSales, "API Application Admin", "java and String MVC", "Provides internet banking functionality via a JSON/HTTP API.")

       Rel(apiSales, dbSales, "Reads & writes to", "JDBC")
       Rel(wbSales, apiSales, "Delivers")

}
Rel(sm, wbSales, "Uses", "HTTPS")



System_Boundary(ModuleMarketing, "ReadChat module Marketing User Marketing") {
    Container(wbMarketing, "Web Application", "java and Spring MVC", "Delivers the static content and the internet banking single page application.")
    Container(dbMarketing, "Database", "Relational Database Schema", "Stores user registration information, hashed authentication credentials, access logs, etc.")
    Container(apiMarketing, "API Application", "java and String MVC", "Provides internet banking functionality via a JSON/HTTP API.")
    Rel(apiMarketing, dbMarketing, "Reads & writes to", "JDBC")
    Rel(wbMarketing, apiMarketing, "Delivers")

}

Rel(ma, wbMarketing, "Uses", "HTTPS")

Rel(ModuleLogin,ModuleAdmin, "Uses", "HTTPS")
Rel(ModuleAdmin,ModuleLogin, "Uses", "HTTPS")
Rel(ModuleAdmin,ModuleSales, "Uses", "HTTPS")
Rel(ModuleSales,ModuleAdmin, "Uses", "HTTPS")
Rel(ModuleSales,ModuleMarketing, "Uses", "HTTPS")
Rel(ModuleMarketing,ModuleSales, "Uses", "HTTPS")

@enduml
