@startuml
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Component.puml
' Daniel Luis Cabrera
LAYOUT_WITH_LEGEND()

Container(wbLogin, "Web Application", "java and Spring MVC", "Delivers the static content and the support page application.")
Container(dbLogin, "Database", "Relational Database Schema", "Stores user registration information, ticket logs, etc.")

Container_Boundary(apiLogin, "API Login") {
    Component(ticket, "Ticket Controller", "MVC Rest Controlle", "Allows users to create ticket asking for support and administrators can resolve the users problems")
    Component(security, "Security Component", "Spring Bean", "encrypt and ensure data integrity to save in the bank")

    Rel(ticket, security, "Uses")
    Rel(security, dbLogin, "Read & write to", "JDBC")
}

Rel(wbLogin, ticket, "Uses", "JSON/HTTPS")
@enduml